const ActionTypes = {
  GET_CUSTOMER_REQUEST: "GET_CUSTOMER_REQUEST",
  GET_CUSTOMER_SUCCESS: "GET_CUSTOMER_SUCCESS",
  GET_CUSTOMER_FAIL: "GET_CUSTOMER_FAIL",

  DELETE_CUSTOMER_SUCCESS: "DELETE_CUSTOMER_SUCCESS",
  DELETE_CUSTOMER_FAIL: "DELETE_CUSTOMER_FAIL",
};

export default ActionTypes;
